CC = gcc
TESTFLAGS = -lcheck -g
CFLAGS = -Wall -Wextra -Werror -std=c11 -I -lcheck
TESTFLAGS2 = -lcheck -lm -lpthread -lrt -lsubunit -g
GCOVFLAGS = -fprofile-arcs -ftest-coverage

all: test

s21_matrix.a : matrix/*.c
	$(CC) $(CFLAGS) -g -std=c11 -c matrix/*.c
	ar rcs s21_matrix.a *.o
	rm -rf *.o

test: clean s21_matrix_tests.c matrix/*.c
	$(CC) $(CFLAGS) s21_matrix_tests.c matrix/*.c -o test $(TESTFLAGS)
	./test

gcov_report:
	$(CC) $(GCOVFLAGS) $(CFLAGS) s21_matrix_tests.c matrix/*.c -o test $(TESTFLAGS)
	./test
	lcov -t "test" -o test.info -c -d .
	genhtml -o report test.info
	rm -rf gcovreport gcovreport.info *.gcda *.gcno string_test.gcda string_test.gcno
	open report/index.html
rebuild: clean all

clean: 
	rm -rf *.o test *.a a.out *.gcno *.gcda test.dSYM *.info report

style_check:
	find . -name "*.c" -o -name "*.h" | xargs clang-format -style=Google -n

style:
	find . -name "*.c" -o -name "*.h" | xargs clang-format -style=Google -i


valgrind: clean
	make test && CK_FORK=no valgrind --vgdb=no --leak-check=full --show-reachable=yes --show-leak-kinds=all --track-origins=yes --verbose --read-var-info=yes ./test